const mongoose = require('mongoose');

const GuessSchema = new mongoose.Schema({
    guessername: {type: String,required: true,unique: true},
    date: {type: Date,default: Date.now},
    Week1_oppscore :   {  type: Number,required: true},
    Week2_oppscore :   {  type: Number,required: true},
    Week3_oppscore :   {  type: Number,required: true},
    Week4_oppscore :   {  type: Number,required: true},
    Week5_oppscore :   {  type: Number,required: true},
    Week6_oppscore :   {  type: Number,required: true},
    Week7_oppscore :   {  type: Number,required: true},
    Week8_oppscore :   {  type: Number,required: true},
    Week9_oppscore :   {  type: Number,required: true},
    Week10_oppscore :  {  type: Number,required: true},
    Week11_oppscore :  {  type: Number,required: true},
    Week12_oppscore :  {  type: Number,required: true},
    Week13_oppscore :  {  type: Number,required: true},
    Week14_oppscore :  {  type: Number,required: true},
    Week15_oppscore :  {  type: Number,required: true},
    Week16_oppscore :  {  type: Number,required: true},
    Week17_oppscore :  {  type: Number,required: true},
    Week18_oppscore :  {  type: Number,required: true},
    Week1_teamscore :  {  type: Number,required: true},
    Week2_teamscore :  {  type: Number,required: true},
    Week3_teamscore :  {  type: Number,required: true},
    Week4_teamscore :  {  type: Number,required: true},
    Week5_teamscore :  {  type: Number,required: true},
    Week6_teamscore :  {  type: Number,required: true},
    Week7_teamscore :  {  type: Number,required: true},
    Week8_teamscore :  {  type: Number,required: true},
    Week9_teamscore :  {  type: Number,required: true},
    Week10_teamscore : {  type: Number,required: true},
    Week11_teamscore : {  type: Number,required: true},
    Week12_teamscore : {  type: Number,required: true},
    Week13_teamscore : {  type: Number,required: true},
    Week14_teamscore : {  type: Number,required: true},
    Week15_teamscore : {  type: Number,required: true},
    Week16_teamscore : {  type: Number,required: true},
    Week17_teamscore : {  type: Number,required: true},
    Week18_teamscore : {  type: Number,required: true}
});


module.exports = Guess = mongoose.model('guess', GuessSchema );