const mongoose = require('mongoose');

const GuessSchema = new mongoose.Schema({
    guessername: {
        type: String,
        required: true,
        unique: true
    },
    date: {
        type: Date,
        default: Date.now
    },
    week1_oppscore : {  type: Number,
            required: true},
    week2_oppscore : {  type: Number,
            required: true},
    week3_oppscore : {  type: Number,
            required: true},
    week4_oppscore : {  type: Number,
            required: true},
    week5_oppscore : {  type: Number,
            required: true},
    week6_oppscore : {  type: Number,
            required: true},
    week7_oppscore : {  type: Number,
            required: true},
    week8_oppscore : {  type: Number,
            required: true},
    week9_oppscore : {  type: Number,
            required: true},
    week10_oppscore : {  type: Number,
            required: true},
    week11_oppscore : {  type: Number,
            required: true},
    week12_oppscore : {  type: Number,
            required: true},
    week13_oppscore : {  type: Number,
            required: true},
    week14_oppscore : {  type: Number,
            required: true},
    week15_oppscore : {  type: Number,
            required: true},
    week16_oppscore : {  type: Number,
            required: true},
    week17_oppscore : {  type: Number,
            required: true},
    week1_teamscore : {  type: Number,
            required: true},
    week2_teamscore : {  type: Number,
            required: true},
    week3_teamscore : {  type: Number,
            required: true},
    week4_teamscore : {  type: Number,
            required: true},
    week5_teamscore : {  type: Number,
            required: true},
    week6_teamscore : {  type: Number,
            required: true},
    week7_teamscore : {  type: Number,
            required: true},
    week8_teamscore : {  type: Number,
            required: true},
    week9_teamscore : {  type: Number,
            required: true},
    week10_teamscore : {  type: Number,
            required: true},
    week11_teamscore : {  type: Number,
            required: true},
    week12_teamscore : {  type: Number,
            required: true},
    week13_teamscore : {  type: Number,
            required: true},
    week14_teamscore : {  type: Number,
            required: true},
    week15_teamscore : {  type: Number,
            required: true},
    week16_teamscore : {  type: Number,
            required: true},
    week17_teamscore : {  type: Number,
            required: true}
});


module.exports = Guess = mongoose.model('guess', GuessSchema );